### ISSUE TITLE
kage installation error

### ISSUE THREAD

**Issue by cgroza** [kage-genotyper/kage#14]
I install kage via `pip3` which works fine:

```
pip3 install kage-genotyper
```

However, when I try to run it I get:

```
cgroza@ubuntu:~$ kage
Traceback (most recent call last):
  File "/home/cgroza/.local/bin/kage", line 5, in <module>
    from kage.command_line_interface import main
  File "/home/cgroza/.local/lib/python3.10/site-packages/kage/command_line_interface.py", line 29, in <module>
    from kmer_mapper.command_line_interface import map_bnp
  File "/home/cgroza/.local/lib/python3.10/site-packages/kmer_mapper/command_line_interface.py", line 12, in <module>
    warnings.filterwarnings("ignore", category=np.VisibleDeprecationWarning) 
  File "/home/cgroza/.local/lib/python3.10/site-packages/numpy/__init__.py", line 410, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'VisibleDeprecationWarning'

```

**Comment by eblerjana** [comment]
I'm getting the same error, is there an update on this?

**Comment by ivargr** [comment]
Hi!

I think force installing numpy less than version 2 should solve this issue. I've pushed an update to the kage-genotyper pip package now that solves this (so a force install of kage-genotyper==2.0.7) should also fix it.
